twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    paths:
        '%kernel.project_dir%/templates': templates
    form_themes:
        - 'form/tailwind_2_layout.html.twig'
    globals:
        site_name: 'EspeciESP'

when@test:
    twig:
        strict_variables: true 