security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    
    providers:
        users:
            entity:
                class: App\Entity\Users
                property: email
        admin:
            entity:
                class: App\Entity\Admin
                property: email
        all_users:
            chain:
                providers: ['users', 'admin']

    firewalls:
        main:
            lazy: true
            provider: all_users
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                username_parameter: email
                password_parameter: password
                default_target_path: app_home
            entry_point: form_login
            access_denied_url: /error/403  # Redirige a una página de error personalizada
            logout:
                path: app_logout
                target: app_home

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/panel, roles: ROLE_ADMIN }